---
- name: snmp ro/rw string configuration
  hosts: routers
  gather_facts: no

  tasks:

    - name: ensure that the desired snmp strings are present
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW

    - name: Validate the SNMP strings are present
      ios_command:
        commands:
          - show run | inc snmp
      register: snmp
        
    - name: Output the SNMP config
      debug:
        msg: "{{ snmp }}"
